spring.application.name=server-3
management.endpoints.web.exposure.include=health,prometheus,metrics
server.tomcat.mbeanregistry.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.50,0.95,0.99